config/routes.rb
Rails.application.routes.draw do
  get 'info/about'
  get 'info/diet'

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :workouts

  root 'workouts#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
         
  has_many :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController

    before_filter :about
    def about
        @bmi = (current_user.weight.to_f / ((current_user.height.to_f / 100) * (current_user.height.to_f / 100))).round(2)
        
        @full_distance = current_user.workouts.inject(0) { |total, training| total + training.distance } 
        
        @full_time = current_user.workouts.inject(0) { |total, training| total + training.length }
        
        if current_user.sex == "Male"
            @bmr = (current_user.weight * 10) + (current_user.height * 6.25) - (current_user.age - 5) + 5
        elsif current_user.sex == "Female"
            @bmr = (current_user.weight * 10) + (current_user.height * 6.25) - (current_user.age - 5) - 161
        end
    end

    def diet
        if current_user.activity == "Sedentary"
            if current_user.goals == "Lose Weight"
                @diet_calories = ((@bmr * 1.1) - 300).to_i
            elsif current_user.goals == "Maintain Weight"
                @diet_calories = (@bmr * 1.1).to_i
            elsif current_user.goals == "Add some weight"
                @diet_calories = ((@bmr * 1.1) + 300).to_i
            end
        elsif current_user.activity == "Low"
            if current_user.goals == "Lose Weight"
                @diet_calories = ((@bmr * 1.5) - 300).to_i
            elsif current_user.goals == "Maintain Weight"
                @diet_calories = (@bmr * 1.5).to_i
            elsif current_user.goals == "Add some weight"
                @diet_calories = ((@bmr * 1.5) + 300).to_i
            end
        elsif current_user.activity == "Medium"
            if current_user.goals == "Lose Weight"
                @diet_calories = ((@bmr * 1.7) - 300).to_i
            elsif current_user.goals == "Maintain Weight"
                @diet_calories = (@bmr * 1.7).to_i
            elsif current_user.goals == "Add some weight"
                @diet_calories = ((@bmr * 1.7) + 300).to_i
            end
        elsif current_user.activity == "High"
            if current_user.goals == "Lose Weight"
                @diet_calories = ((@bmr * 2.1) - 300).to_i
            elsif current_user.goals == "Maintain Weight"
                @diet_calories = (@bmr * 2.1).to_i
            elsif current_user.goals == "Add some weight"
                @diet_calories = ((@bmr * 2.1) + 300).to_i
            end
        end

        if @bmi <= 18.5
            @bmi_norm = "Underweight"
        elsif @bmi > 18.5 && @bmi <= 25
            @bmi_norm = "Normal/Healthy Weight"
        elsif @bmi > 25 && @bmi <= 30
            @bmi_norm = "Overweight"
        elsif @bmi > 30
            @bmi_norm = "Obese"
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :avatar, :goals, :surname, :email, :password, :password_confirmation, :weight, :activity, :height, :age, :sex)
  end

  def account_update_params
    params.require(:user).permit(:name, :avatar, :goals,  :surname, :email, :password, :password_confirmation, :activity, :current_password, :weight, :height, :age, :sex)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :find_training, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @workouts = current_user.present? ? current_user.workouts.all : []
    end
    
    def show
        if current_user.sex == "Male"
            if @workout.intensity == "High"
                @calories = (((current_user.age * 0.2017) - (current_user.weight * 0.09036) + (165 * 0.6309) - 55.0969) * @workout.length / 4.184).round(2)
            elsif @workout.intensity == "Normal"
                @calories = (((current_user.age * 0.2017) - (current_user.weight * 0.09036) + (145 * 0.6309) - 55.0969) * @workout.length / 4.184).round(2)
            elsif @workout.intensity == "Low"
                @calories = (((current_user.age * 0.2017) - (current_user.weight * 0.09036) + (125 * 0.6309) - 55.0969) * @workout.length / 4.184).round(2) 
            end
        else
            if @workout.intensity == "High"
                @calories = (((current_user.age * 0.074) - (current_user.weight * 0.05741) + (165 * 0.4472) - 20.4022) * @workout.length / 4.184).round(2)
            elsif @workout.intensity == "Normal"
                @calories = (((current_user.age * 0.074) - (current_user.weight * 0.05741) + (145 * 0.4472) - 20.4022) * @workout.length / 4.184).round(2)
            elsif @workout.intensity == "Low"
                @calories = (((current_user.age * 0.074) - (current_user.weight * 0.05741) + (125 * 0.4472) - 20.4022) * @workout.length / 4.184).round(2)
            end
        end
    end
    
    def new 
        @workout = current_user.workouts.build
    end
    
    def create 
         @workout = current_user.workouts.build(workout_params)
         if @workout.save
             redirect_to @workout
         else
             render 'new'
         end
    end
    
    def edit 
    end
    
    def update
        if @workout.update(workout_params)
            redirect_to @workout
        else
            render 'edit'
        end
    end
    
    def destroy
        @workout.destroy
        redirect_to root_path
    end
    
    private
    
    def workout_params
        params.require(:workout).permit(:date, :workout, :comment, :mood, :length, :weather, :distance, :intensity)
    end
    
    def find_training
        @workout = Workout.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
	def sessions_chart_data
 		(3.weeks.ago.to_date..Date.today).map do |date|
 			{
 				date: date,
 				distance: Workout.where("date(date) = ?", date).sum(:distance)
 			}
 		end
	end

	def running_chart_data
 		(3.weeks.ago.to_date..Date.today).map do |date|
	    {
	        date: date,
	        distance: Workout.where(workout: "Running", date: date.beginning_of_day..date.end_of_day).sum(:distance)
	    }
	  end
	end

	def swimming_chart_data
 		(3.weeks.ago.to_date..Date.today).map do |date|
	    {
	        date: date,
	        distance: Workout.where(workout: "Swimming", date: date.beginning_of_day..date.end_of_day).sum(:distance)
	    }
	  end
	end

	def distance_chart_data
 		(3.weeks.ago.to_date..Date.today).map do |date|
	    {
	        date: date,
	        distance_c: Workout.where(workout: "Cycling", date: date.beginning_of_day..date.end_of_day).sum(:distance),
					distance_r: Workout.where(workout: "Running", date: date.beginning_of_day..date.end_of_day).sum(:distance),
				  distance_s: Workout.where(workout: "Swimming", date: date.beginning_of_day..date.end_of_day).sum(:distance)
	    }
	  end
	end
end

app/views/info/about.html.erb
<div class="row about">

	<div class="about_header">
		<%= image_tag current_user.avatar.url(:medium) %>
		<h2><%= current_user.name%> <%= current_user.surname %>, <%= current_user.age %></h2>
	</div>

	<div class="col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3 about_details">
		<p><span> Weight : </span><%=current_user.weight%> kg</p>
		<p><span> Height : </span><%=current_user.height%> cm</p>
		<p><span> Gender : </span><%=current_user.sex%></p>

		<div class="line"></div>

		<p><span> Daily activity : </span><%= current_user.activity %></p>
		<p><span> Diet goal : </span><%= current_user.goals %></p>
		<p><span> BMI : </span><%= @bmi %></p>
		<p><span> BMR : </span><%= @bmr %> </p>

		<div class="line"></div>

		<p><span> All training sessions : </span><%= current_user.workouts.count %></p>
		<p><span> All distance : </span><%= @full_distance %> km</p>
		<p><span> All time in trainings : </span><%= @full_time %> min</p>
	</div>
</div>

app/views/info/diet.html.erb
<div class="row diet">
	<div class="diet_header">
		<h1>Diet goal: "<%= current_user.goals %>"</h1>
	</div>
	<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1 diet_details">

		<h2>You should eat <%= @diet_calories %> kcal, because your daily activity is "<%= current_user.activity %>"</h2>
		
		<div class="diet-line"></div>
		
		<h2> We recommend to eat 60% carbs, 20% protein and 20% fat.
		 In your case, Carbs = <%= (@diet_calories * 0.6).round(1) %> kcal, Protein = <%= (@diet_calories * 0.2).round(1)%> kcal, Fat = <%= (@diet_calories * 0.2).round(1)%> kcal.</h3>

		<div id="diet-circle"></div>

		<h2> Your bmi = <%=@bmi%>. Weight status: "<%=@bmi_norm%>".</h2>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="row footer">
  <div class="col-sm-9 col-xs-9">
    <h2>FitView</h2>
    <p>&copy; 2016 FitView, Inc. All rights reserved.</p>
    <h6>Created by <%= link_to "Radosz Szymon", "https://github.com/RadoszSzymon", target:"_blank" %></h6>
  </div>
  <div class="col-sm-1 col-xs-1 icon wow slideInRight" data-wow-duration="1s">
    <%= link_to "https://github.com/RadoszSzymon", class:"social_link", target:"_blank" do %>
      <%= fa_icon "facebook" %>
    <%end%>
  </div>
  <div class="col-sm-1 col-xs-1 icon wow slideInRight" data-wow-duration="1.1s">
    <%= link_to "https://github.com/RadoszSzymon", class:"social_link", target:"_blank" do %>
      <%= fa_icon "twitter" %>
    <%end%>
  </div>
  <div class="col-sm-1 col-xs-1 icon wow slideInRight" data-wow-duration="1.2s">
    <%= link_to "https://github.com/RadoszSzymon", class:"social_link", target:"_blank" do %>
      <%= fa_icon "instagram" %>
    <%end%>
  </div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-findcond">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png"), root_path, class:"logo" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="option"><%= link_to "New Training", new_workout_path %></li>
        <li class="option"><%= link_to "My Info", info_about_path %></li>
        <li class="option"><%= link_to "My Diet Plan", info_diet_path %></li>
        <li class="option"><%= link_to "Update My Info",edit_user_registration_path %></li>
        <li class="option"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Workout Log Application</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag "https://www.google.com/jsapi" %>

		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<!-- marker google font -->
		<link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

		<!-- raleway google font -->
		<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

		<!-- graphs -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
	</head>

	<body>
		<% if user_signed_in? %>
			<%= render 'layouts/menu' %>
		<% end %>

		<div class="container">
		  	<div class="jumbotron">
		  		<%= yield %>

					<%= render 'layouts/footer' %>
		  	</div>
		</div>

		<!-- js scripts -->

		<script>
			new Morris.Line({
			  element: 'distance_chart',
			  resize: true,
			  data: $('#distance_chart').data('distance'),
			  xkey: 'date',
			  ykeys: ['distance_c', 'distance_r', 'distance_s'],
			  labels: ['Cycling distance [km]', 'Running distance [km]', 'Swimming distance [km]']
			});
		</script>

		<script>
			new Morris.Donut({
			  element: 'diet-circle',
			  resize: true,
			  data: [
			    {label: "Carbs", value: Math.round((<%= @diet_calories %> * 0.6)) },
			    {label: "Protein", value: Math.round((<%= @diet_calories%> * 0.2)) },
			    {label: "Fat", value: Math.round((<%= @diet_calories %>* 0.2)) }
			  ]
			});
		</script>

		<!-- wow.js library -->
		<script>
			new WOW().init();
		</script>

	</body>
</html>

app/views/workouts/_form.html.erb
<%= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.input :date, label: "Date"%>
	<%= f.input :workout, label: "What training?", :collection => ["Running","Swimming","Cycling"]%>
	<%= f.input :mood, label: "Your mood", :collection => ["Great","Good","Bad"]%>
	<%= f.input :weather, label: "Weather:", :collection => ["Sunny","Rainy","Cloudy"] %>
	<%= f.input :intensity, label: "Intensity. Low is 90-120BPM. Normal is 120-155BPM. High is 155+BPM.", :collection => ["High","Normal","Low"]%>
	<%= f.input :length, label: "Time in minutes:", input_html: { class: "form-control" }%>
	<%= f.input :distance, label: "Distance in kilometers:", input_html: { class: "form-control" }%>
	<%= f.input :comment, label: "Your comment to this training session:", input_html: { class: "form-control" }%>
	<br>
	<%= f.button :submit %>
<% end %>

app/views/workouts/edit.html.erb
<div class="row edit_training">
  <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
    <h1>Edit Training</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/workouts/index.html.erb
<div class="row index">
	<% if user_signed_in? %>
		<div class="col-sm-12 index_signed_in">
			<h1>Last 3 weeks sessions graph</h1>

			<%= content_tag :div, "", id: "distance_chart", data: {distance: distance_chart_data} %>

			<h1>Training History</h1>

			<% @workouts.each do |workout| %>
				<div class="training_index wow slideInUp"  data-wow-duration="0.8s">
					<h2><%= link_to workout.workout, workout %></h2>
					<h4><%= link_to workout.date, workout %></h4>
				</div>
				<hr>
			<% end %>
		</div>
	<% else %>
		<div class="col-sm-12 index_not_signed_in">

			<div class="row banner">
					<h1>START YOUR JOURNEY <br/> TO HEALTHY LIFE</h1>
					<div class="col-sm-4 col-sm-offset-1 col-xs-8 col-xs-offset-2">
						<%= link_to "SIGN UP FOR FREE", new_user_registration_path, class: "btn btn-default signup"%>
					</div>
					<div class="col-sm-4 col-sm-offset-1 col-xs-8 col-xs-offset-2">
						<%= link_to "SIGN IN", new_user_session_path, class: "btn btn-default login"%>
					</div>
			</div>

			<div class="row service">
				<h1>How it works?</h1>
				<div class="line">
					<ul>
						<li class="wow slideInRight" data-wow-duration="1s">Add your training details</li>
						<li class="wow slideInRight" data-wow-duration="1.1s">Calculate session parameters</li>
						<li class="wow slideInRight" data-wow-duration="1.2s">Control amount of calories</li>
						<li class="wow slideInRight" data-wow-duration="1.3s">Analyse session graphs</li>
						<li class="wow slideInRight" data-wow-duration="1.4s">Be proud of better shape</li>
					</ul>
				</div>
			</div>

			<div class="row newsletter">
				<h2>Sign Up for newsletter</h2>
				<div class="newsletter_form">
					<div class="col-sm-5 col-sm-offset-1 col-xs-12">
						<input type="text" class="form-control" placeholder="Address e-mail" class="newsletter-input">
					</div>
					<div class="col-sm-5 col-xs-12">
						<div class="btn btn-default newsletter_button">SEND</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/workouts/new.html.erb
<div class="row new">
	<h1 class="new_header"> New Training </h1>
	<div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2 new_details">
		<%= render 'form' %>
	</div>
</div>

app/views/workouts/show.html.erb
<div class="row training">
    <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
        <p><strong> Date: </strong> <%= @workout.date.strftime("%Y-%m-%d %H:%M") %></p>
        <p> <strong> What training: </strong> <%= @workout.workout %></p>
        <p> <strong> Your mood: </strong> <%= @workout.mood %></p>
        <p> <strong> Weather: </strong> <%= @workout.weather %></p>
        <p> <strong> Intensity: </strong> <%= @workout.intensity %> </p>
        <p> <strong> Time: </strong> <%= @workout.length %> min</p>
        <p> <strong> Distance: </strong> <%= @workout.distance %> km</p>
        <p> <strong> Average speed: </strong> <%= (@workout.distance.to_f/(@workout.length.to_f/60)).to_f.round(3) %> km/h</p>
        <p> <strong> Average amount of burned calories: </strong> <%= @calories %> kcal</p>
        <p> <strong> Comment: </strong> <%= @workout.comment %></p>

        <%= link_to "Edit", edit_workout_path(@workout), class:"btn btn-default" %>
        <%=link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-default"  %>
    </div>
</div>